directive @role(is: Role = HERO) on FIELD_DEFINITION | OBJECT

enum Role {
  HERO
  VILLAN
}

interface Character {
  id: ID!
  name: String!
  description: String!
}

type Hero implements Character @role(is: HERO) {
  id: ID!
  name: String!
  description: String!
  allies @include(if: $hasAllies) {
    ...heroHasAllies
  }
}

type Villan implements Character @role(is: VILLAN) {
  id: ID!
  name: String!
  description: String!
  allies @include(if: $hasAllies) {
    ...villanHasAllies
  }
}

fragment heroHasAllies on Hero {
  id: ID!
  name: String!
  description: String!
  role: String! @role(is: HERO)
}

fragment villanHasAllies on Villan {
  id: ID!
  name: String!
  description: String!
  role: String! @role(is: VILLAN)
}